[2025-06-09 13:55:46,657: INFO: main: welcome to custom log]
[2025-06-10 14:16:07,818: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-10 14:16:07,829: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-10 14:16:07,829: INFO: common: created directory at: artifacts]
[2025-06-10 14:16:07,835: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-10 14:16:07,835: INFO: 2140807067: Downloading data from https://drive.google.com/file/d/1sTXnAViiu4j7dxh3xKb4xAA_vmQasNnL/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-10 14:16:42,561: INFO: 2140807067: Downloaded data from https://drive.google.com/file/d/1sTXnAViiu4j7dxh3xKb4xAA_vmQasNnL/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-10 14:37:13,486: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-10 14:37:13,487: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-10 14:37:13,488: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-10 14:37:13,488: INFO: common: created directory at: artifacts]
[2025-06-10 14:37:13,488: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-10 14:37:13,489: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "C:\Users\suraj\kidney-Disease-Classification\src\CnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "C:\Users\suraj\kidney-Disease-Classification\src\CnnClassifier\components\Data_Ingestion.py", line 30, in download_file
    raise e
  File "C:\Users\suraj\kidney-Disease-Classification\src\CnnClassifier\components\Data_Ingestion.py", line 20, in download_file
    os.makedirs("artifacts/data_ingestion", exist_ok=True)
NameError: name 'os' is not defined
[2025-06-10 14:38:25,961: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-10 14:38:25,962: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-10 14:38:25,962: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-10 14:38:25,962: INFO: common: created directory at: artifacts]
[2025-06-10 14:38:25,962: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-10 14:38:25,962: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "C:\Users\suraj\Kidney-Disease-classification\main.py", line 9, in <module>
    data_ingestion.main()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\Data_Ingestion.py", line 30, in download_file
    raise e
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\Data_Ingestion.py", line 20, in download_file
    os.makedirs("artifacts/data_ingestion", exist_ok=True)
NameError: name 'os' is not defined
[2025-06-10 14:39:03,684: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-10 14:39:03,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-10 14:39:03,685: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-10 14:39:03,685: INFO: common: created directory at: artifacts]
[2025-06-10 14:39:03,687: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-10 14:39:03,687: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "C:\Users\suraj\Kidney-Disease-classification\main.py", line 9, in <module>
    data_ingestion.main()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\Data_Ingestion.py", line 30, in download_file
    raise e
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\Data_Ingestion.py", line 20, in download_file
    os.makedirs("artifacts/data_ingestion", exist_ok=True)
NameError: name 'os' is not defined
[2025-06-10 14:40:17,481: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-10 14:40:17,481: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-10 14:40:17,482: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-10 14:40:17,482: INFO: common: created directory at: artifacts]
[2025-06-10 14:40:17,482: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-10 14:40:17,483: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "C:\Users\suraj\Kidney-Disease-classification\main.py", line 10, in <module>
    data_ingestion.main()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\Data_Ingestion.py", line 30, in download_file
    raise e
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\Data_Ingestion.py", line 20, in download_file
    os.makedirs("artifacts/data_ingestion", exist_ok=True)
NameError: name 'os' is not defined
[2025-06-10 14:42:10,953: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-10 14:42:10,953: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-10 14:42:10,955: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-10 14:42:10,955: INFO: common: created directory at: artifacts]
[2025-06-10 14:42:10,955: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-10 14:42:10,957: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1sTXnAViiu4j7dxh3xKb4xAA_vmQasNnL/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-10 14:42:47,555: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1sTXnAViiu4j7dxh3xKb4xAA_vmQasNnL/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-10 14:42:55,429: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-11 10:20:41,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-11 10:20:41,933: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-11 10:20:41,940: INFO: common: created directory at: artifacts]
[2025-06-11 10:20:41,943: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-11 10:20:45,964: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-11 10:36:29,191: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-11 10:36:29,193: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-11 10:36:29,194: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-11 10:36:29,195: INFO: common: created directory at: artifacts]
[2025-06-11 10:36:29,195: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-11 10:36:29,195: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1sTXnAViiu4j7dxh3xKb4xAA_vmQasNnL/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-11 10:36:58,778: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1sTXnAViiu4j7dxh3xKb4xAA_vmQasNnL/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-11 10:37:06,571: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-11 10:37:06,571: INFO: main: *******************]
[2025-06-11 10:37:06,571: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-11 10:37:06,572: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-11 10:37:06,573: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-11 10:37:06,573: INFO: common: created directory at: artifacts]
[2025-06-11 10:37:06,573: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-11 10:37:06,968: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-11 10:37:07,209: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-11 15:13:38,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-11 15:13:38,484: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-11 15:13:38,488: INFO: common: created directory at: artifacts]
[2025-06-11 15:13:38,488: INFO: common: created directory at: artifacts\training]
[2025-06-12 09:48:43,799: INFO: stage_03_model_training: *******************]
[2025-06-12 09:48:43,799: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-12 09:48:43,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 09:48:43,803: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 09:48:43,803: INFO: common: created directory at: artifacts]
[2025-06-12 09:48:43,804: INFO: common: created directory at: artifacts\training]
[2025-06-12 09:48:43,804: ERROR: stage_03_model_training: No file or directory found at artifacts\prepare_base_model\base_model_updated.h5]
Traceback (most recent call last):
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\pipeline\stage_03_model_training.py", line 37, in <module>
    model_trainer.main()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\pipeline\stage_03_model_training.py", line 16, in main
    training.get_base_model()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\model_training.py", line 15, in get_base_model
    self.model = tf.keras.models.load_model(
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\prepare_base_model\base_model_updated.h5
[2025-06-12 09:51:14,599: INFO: stage_03_model_training: *******************]
[2025-06-12 09:51:14,599: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-12 09:51:14,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 09:51:14,602: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 09:51:14,602: INFO: common: created directory at: artifacts]
[2025-06-12 09:51:14,602: INFO: common: created directory at: artifacts\training]
[2025-06-12 09:51:14,603: ERROR: stage_03_model_training: No file or directory found at artifacts\prepare_base_model\base_model_updated.h5]
Traceback (most recent call last):
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\pipeline\stage_03_model_training.py", line 37, in <module>
    model_trainer.main()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\pipeline\stage_03_model_training.py", line 16, in main
    training.get_base_model()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\model_training.py", line 15, in get_base_model
    self.model = tf.keras.models.load_model(
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\prepare_base_model\base_model_updated.h5
[2025-06-12 09:57:27,238: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-12 09:57:27,240: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 09:57:27,241: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 09:57:27,241: INFO: common: created directory at: artifacts]
[2025-06-12 09:57:27,241: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-12 09:57:27,241: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1sTXnAViiu4j7dxh3xKb4xAA_vmQasNnL/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 09:57:55,671: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1sTXnAViiu4j7dxh3xKb4xAA_vmQasNnL/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 09:58:06,111: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-12 09:58:06,111: INFO: main: *******************]
[2025-06-12 09:58:06,111: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-12 09:58:06,114: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 09:58:06,115: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 09:58:06,116: INFO: common: created directory at: artifacts]
[2025-06-12 09:58:06,116: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-12 09:58:06,941: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-12 09:58:07,287: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-12 09:58:07,288: INFO: main: *******************]
[2025-06-12 09:58:07,288: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-12 09:58:07,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 09:58:07,292: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 09:58:07,292: INFO: common: created directory at: artifacts]
[2025-06-12 09:58:07,293: INFO: common: created directory at: artifacts\training]
[2025-06-12 09:58:07,965: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "C:\Users\suraj\Kidney-Disease-classification\main.py", line 32, in <module>
    model_trainer.main()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\pipeline\stage_03_model_training.py", line 16, in main
    training.train_valid_generator()
  File "C:\Users\suraj\Kidney-Disease-classification\src\CnnClassifier\components\model_training.py", line 36, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-06-12 10:14:20,800: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-12 10:14:20,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 10:14:20,804: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 10:14:20,805: INFO: common: created directory at: artifacts]
[2025-06-12 10:14:20,805: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-12 10:14:20,805: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 10:14:31,946: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 10:14:34,392: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-12 10:14:34,392: INFO: main: *******************]
[2025-06-12 10:14:34,392: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-12 10:14:34,393: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 10:14:34,394: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 10:14:34,394: INFO: common: created directory at: artifacts]
[2025-06-12 10:14:34,395: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-12 10:14:34,932: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-12 10:14:35,124: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-12 10:14:35,124: INFO: main: *******************]
[2025-06-12 10:14:35,124: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-12 10:14:35,125: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 10:14:35,126: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 10:14:35,127: INFO: common: created directory at: artifacts]
[2025-06-12 10:14:35,127: INFO: common: created directory at: artifacts\training]
[2025-06-12 10:23:24,516: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-12 10:48:01,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 10:48:01,364: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 10:48:01,369: INFO: common: created directory at: artifacts]
[2025-06-12 10:51:30,622: INFO: common: json file saved at: scores.json]
[2025-06-12 10:51:33,203: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-06-12 10:51:33,953: INFO: builder_impl: Assets written to: C:\Users\suraj\AppData\Local\Temp\tmp5hfo1r6v\model\data\model\assets]
[2025-06-12 11:24:18,280: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-12 11:24:18,281: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 11:24:18,282: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 11:24:18,282: INFO: common: created directory at: artifacts]
[2025-06-12 11:24:18,283: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-12 11:24:18,283: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 11:24:30,635: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 11:24:32,746: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-12 11:24:32,747: INFO: main: *******************]
[2025-06-12 11:24:32,747: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-12 11:24:32,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 11:24:32,749: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 11:24:32,749: INFO: common: created directory at: artifacts]
[2025-06-12 11:24:32,749: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-12 11:24:33,235: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-12 11:24:33,420: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-12 11:24:33,420: INFO: main: *******************]
[2025-06-12 11:24:33,420: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-12 11:24:33,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 11:24:33,423: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 11:24:33,423: INFO: common: created directory at: artifacts]
[2025-06-12 11:24:33,423: INFO: common: created directory at: artifacts\training]
[2025-06-12 12:14:00,585: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-12 12:14:00,586: INFO: main: *******************]
[2025-06-12 12:14:00,587: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-12 12:14:00,597: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 12:14:00,602: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 12:14:00,605: INFO: common: created directory at: artifacts]
[2025-06-12 12:18:18,696: INFO: common: json file saved at: scores.json]
[2025-06-12 12:18:18,698: INFO: common: json file saved at: scores.json]
[2025-06-12 12:18:18,698: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-12 12:31:21,952: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-12 12:31:21,953: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 12:31:21,954: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 12:31:21,955: INFO: common: created directory at: artifacts]
[2025-06-12 12:31:21,955: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-12 12:31:21,955: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 12:31:38,247: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 12:31:40,406: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-12 12:31:40,406: INFO: main: *******************]
[2025-06-12 12:31:40,406: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-12 12:31:40,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 12:31:40,408: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 12:31:40,409: INFO: common: created directory at: artifacts]
[2025-06-12 12:31:40,409: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-12 12:31:40,851: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-12 12:31:41,031: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-12 12:31:41,031: INFO: main: *******************]
[2025-06-12 12:31:41,031: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-12 12:31:41,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 12:31:41,034: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 12:31:41,034: INFO: common: created directory at: artifacts]
[2025-06-12 12:31:41,034: INFO: common: created directory at: artifacts\training]
[2025-06-12 12:40:23,842: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-12 12:40:23,843: INFO: main: *******************]
[2025-06-12 12:40:23,843: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-12 12:40:23,846: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 12:40:23,847: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 12:40:23,848: INFO: common: created directory at: artifacts]
[2025-06-12 12:43:04,853: INFO: common: json file saved at: scores.json]
[2025-06-12 12:43:04,856: INFO: common: json file saved at: scores.json]
[2025-06-12 12:43:06,678: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-06-12 12:43:07,162: INFO: builder_impl: Assets written to: C:\Users\suraj\AppData\Local\Temp\tmpvxx4elij\model\data\model\assets]
[2025-06-12 12:43:25,568: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-12 13:59:13,332: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-12 13:59:13,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 13:59:13,332: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 13:59:13,332: INFO: common: created directory at: artifacts]
[2025-06-12 13:59:13,332: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-12 13:59:13,332: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 13:59:26,129: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 13:59:28,172: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-12 13:59:28,172: INFO: main: *******************]
[2025-06-12 13:59:28,172: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-12 13:59:28,172: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 13:59:28,172: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 13:59:28,172: INFO: common: created directory at: artifacts]
[2025-06-12 13:59:28,172: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-12 13:59:28,588: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-12 13:59:28,793: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-12 13:59:28,793: INFO: main: *******************]
[2025-06-12 13:59:28,793: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-06-12 13:59:28,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 13:59:28,802: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 13:59:28,802: INFO: common: created directory at: artifacts]
[2025-06-12 13:59:28,802: INFO: common: created directory at: artifacts\training]
[2025-06-12 14:11:20,501: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-12 14:11:20,501: INFO: main: *******************]
[2025-06-12 14:11:20,501: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-12 14:11:20,509: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 14:11:20,513: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 14:11:20,513: INFO: common: created directory at: artifacts]
[2025-06-12 14:14:17,653: INFO: common: json file saved at: scores.json]
[2025-06-12 14:14:17,662: INFO: common: json file saved at: scores.json]
[2025-06-12 14:14:21,997: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-06-12 14:14:22,799: INFO: builder_impl: Assets written to: C:\Users\suraj\AppData\Local\Temp\tmp3gfn0tuc\model\data\model\assets]
[2025-06-12 14:14:33,776: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-12 14:20:45,965: INFO: stage_04_model_evaluation: *******************]
[2025-06-12 14:20:45,965: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-12 14:20:45,965: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 14:20:45,965: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 14:20:45,974: INFO: common: created directory at: artifacts]
[2025-06-12 14:23:51,558: INFO: common: json file saved at: scores.json]
[2025-06-12 14:23:51,560: INFO: common: json file saved at: scores.json]
[2025-06-12 14:23:52,913: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-06-12 14:23:53,366: INFO: builder_impl: Assets written to: C:\Users\suraj\AppData\Local\Temp\tmpgi8ie7rl\model\data\model\assets]
[2025-06-12 14:24:01,100: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-12 14:39:32,572: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-12 14:39:32,572: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 14:39:32,572: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 14:39:32,572: INFO: common: created directory at: artifacts]
[2025-06-12 14:39:32,572: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-12 14:39:32,572: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 14:39:45,063: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 14:39:47,168: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-12 14:45:10,493: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-12 14:45:10,493: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 14:45:10,493: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 14:45:10,493: INFO: common: created directory at: artifacts]
[2025-06-12 14:45:10,493: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-12 14:45:10,493: INFO: Data_Ingestion: Downloading data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 14:45:23,750: INFO: Data_Ingestion: Downloaded data from https://drive.google.com/file/d/1Q2AVsKJ77DDOfM_AQVCO9C-dnsmbAX2L/view?usp=sharing into file artifacts/data_ingestion/dataset.zip]
[2025-06-12 14:45:25,867: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-12 14:45:37,700: INFO: stage_02_prepare_base_model: *******************]
[2025-06-12 14:45:37,700: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-12 14:45:37,702: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 14:45:37,704: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 14:45:37,704: INFO: common: created directory at: artifacts]
[2025-06-12 14:45:37,704: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-12 14:45:38,206: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-12 14:45:38,535: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-12 14:46:17,754: INFO: stage_03_model_training: *******************]
[2025-06-12 14:46:17,754: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-06-12 14:46:17,754: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 14:46:17,760: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 14:46:17,760: INFO: common: created directory at: artifacts]
[2025-06-12 14:46:17,760: INFO: common: created directory at: artifacts\training]
[2025-06-12 14:56:50,225: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-12 14:56:57,268: INFO: stage_04_model_evaluation: *******************]
[2025-06-12 14:56:57,268: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-12 14:56:57,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-12 14:56:57,273: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-12 14:56:57,273: INFO: common: created directory at: artifacts]
[2025-06-12 14:59:28,177: INFO: common: json file saved at: scores.json]
[2025-06-12 14:59:28,177: INFO: common: json file saved at: scores.json]
[2025-06-12 14:59:29,730: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-06-12 14:59:30,312: INFO: builder_impl: Assets written to: C:\Users\suraj\AppData\Local\Temp\tmpg6ptkwa4\model\data\model\assets]
[2025-06-12 14:59:37,584: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-12 15:18:36,963: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.0.8.202:8080]
[2025-06-12 15:18:36,963: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-12 15:18:55,228: INFO: _internal: 127.0.0.1 - - [12/Jun/2025 15:18:55] "GET / HTTP/1.1" 200 -]
[2025-06-12 15:19:09,581: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\suraj\kidney-Disease-classification\src\CnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-06-12 15:19:09,698: INFO: _internal: 127.0.0.1 - - [12/Jun/2025 15:19:09] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-12 15:26:04,177: INFO: _internal: 127.0.0.1 - - [12/Jun/2025 15:26:04] "GET / HTTP/1.1" 200 -]
[2025-06-12 15:26:09,188: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\suraj\kidney-Disease-classification\src\CnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-06-12 15:26:09,191: INFO: _internal: 127.0.0.1 - - [12/Jun/2025 15:26:09] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-12 15:26:19,966: INFO: _internal: 127.0.0.1 - - [12/Jun/2025 15:26:19] "GET / HTTP/1.1" 200 -]
[2025-06-12 15:43:27,531: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.0.8.202:8080]
[2025-06-12 15:43:27,531: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-12 15:43:41,587: INFO: _internal: 127.0.0.1 - - [12/Jun/2025 15:43:41] "GET / HTTP/1.1" 200 -]
